In [4]:
with open('/content/EDA_Online_Retail_II_Report.md', 'r') as f:
    report_content = f.read()

{report_content}

## 📝 Chuẩn Bị Dữ Liệu (Data Preparation)

Phần này sẽ thực hiện các bước tiền xử lý dữ liệu được đề cập trong báo cáo EDA, mục **4. 🧹 Xử Lý Dữ Liệu (Data Preprocessing)**.

In [5]:
import pandas as pd
import numpy as np

# Đường dẫn đến file dữ liệu
# Vui lòng cập nhật đường dẫn chính xác của file 'online_retail_II.xlsx' nếu nó không nằm trong thư mục gốc của Colab.
file_path = '/content/online_retail_II.xlsx' # Giả định file nằm trong /content/

# Tải dữ liệu từ file Excel. Có 2 sheet, cần đọc sheet 'Year 2009-2010' và 'Year 2010-2011'
# Tuy nhiên, báo cáo EDA không chỉ rõ sheet nào, và thường file này có 2 sheet.
# Tôi sẽ đọc sheet đầu tiên hoặc nếu file chỉ có 1 sheet chứa dữ liệu. Nếu có nhiều sheet, cần thêm bước ghép nối.

# Thử đọc trực tiếp, nếu lỗi vì nhiều sheet, tôi sẽ điều chỉnh.
try:
    df_cleaned = pd.read_excel(file_path)
    print("Đã tải dữ liệu thành công từ sheet mặc định.")
except ValueError as e:
    if "Multiple sheets found" in str(e):
        print("Phát hiện nhiều sheet. Đang đọc sheet 'Year 2010-2011' (thường là sheet chính).")
        df_cleaned = pd.read_excel(file_path, sheet_name='Year 2010-2011')
    else:
        print(f"Lỗi khi tải file: {e}")
        # Có thể thêm logic để yêu cầu người dùng chọn sheet hoặc ghép nối các sheet



print(f"Kích thước ban đầu của DataFrame: {df_cleaned.shape}")
display(df_cleaned.head())

Đã tải dữ liệu thành công từ sheet mặc định.
Kích thước ban đầu của DataFrame: (525461, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

### 4.1. Thay đổi tên cột (Rename Columns)

Báo cáo EDA không chỉ định tên cột cụ thể cần thay đổi. Nếu các cột có tên tiếng Việt hoặc định dạng không chuẩn, bạn có thể thực hiện đổi tên tại đây. Hiện tại, tôi sẽ giả định các cột đã có tên tiếng Anh chuẩn hoặc tên cần thiết. Nếu có yêu cầu cụ thể, vui lòng cung cấp.

In [6]:
# Kiểm tra tên cột hiện tại
print("Tên cột hiện tại:", df_cleaned.columns.tolist())

# Ví dụ nếu cần đổi tên:
# df_cleaned = df_cleaned.rename(columns={'Mã hóa đơn': 'InvoiceNo', 'Mô tả': 'Description', ...})

print("Kích thước DataFrame sau bước này: ", df_cleaned.shape)
display(df_cleaned.head())

Tên cột hiện tại: ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']
Kích thước DataFrame sau bước này:  (525461, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

### 4.2. Xóa các hàng trùng lặp (Remove Duplicate Rows)

Loại bỏ các hàng có giá trị trùng lặp hoàn toàn trong DataFrame.

In [7]:
print(f"Số hàng trước khi xóa trùng lặp: {df_cleaned.shape[0]}")
df_cleaned.drop_duplicates(inplace=True)
print(f"Số hàng sau khi xóa trùng lặp: {df_cleaned.shape[0]}")
print("Kích thước DataFrame sau bước này: ", df_cleaned.shape)
display(df_cleaned.head())

Số hàng trước khi xóa trùng lặp: 525461
Số hàng sau khi xóa trùng lặp: 518596
Kích thước DataFrame sau bước này:  (518596, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

### 4.3. Xử lý thiếu dữ liệu (Handle Missing Data)

- Xóa các hàng có `CustomerID` trống.
- Xóa các hàng có `Description` trống.

In [10]:
print("Kiểm tra giá trị thiếu trước khi xử lý:")
display(df_cleaned.isnull().sum())

initial_rows = df_cleaned.shape[0]

# Xóa các hàng có CustomerID trống
df_cleaned.dropna(subset=['Customer ID'], inplace=True)
print(f"Số hàng sau khi xóa Customer ID trống: {df_cleaned.shape[0]}")

# Xóa các hàng có Description trống
df_cleaned.dropna(subset=['Description'], inplace=True)
print(f"Số hàng sau khi xóa Description trống: {df_cleaned.shape[0]}")

print(f"Tổng số hàng đã xóa do thiếu dữ liệu: {initial_rows - df_cleaned.shape[0]}")
print("Kích thước DataFrame sau bước này: ", df_cleaned.shape)
display(df_cleaned.head())

Kiểm tra giá trị thiếu trước khi xử lý:

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107833
Country             0
dtype: int64

Số hàng sau khi xóa Customer ID trống: 410763
Số hàng sau khi xóa Description trống: 410763
Tổng số hàng đã xóa do thiếu dữ liệu: 107833
Kích thước DataFrame sau bước này:  (410763, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

### 4.4. Xử lý dữ liệu không hợp lệ (Handle Invalid Data)

- `InvoiceNo`: Loại bỏ các hàng có `InvoiceNo` chứa chữ cái (Hàng trả lại).
- `Quantity`: Xóa các hàng có `Quantity` <= 0.
- `Price`: Xóa các hàng có `Price` <= 0.

In [12]:
initial_rows = df_cleaned.shape[0]

# Loại bỏ các hàng có Invoice chứa chữ cái (Hàng trả lại)
# Chuyển Invoice sang string trước khi kiểm tra
df_cleaned = df_cleaned[~df_cleaned['Invoice'].astype(str).str.contains('[A-Za-z]', na=False)]
print(f"Số hàng sau khi loại bỏ Invoice có chữ cái: {df_cleaned.shape[0]}")

# Xóa các hàng có Quantity <= 0
df_cleaned = df_cleaned[df_cleaned['Quantity'] > 0]
print(f"Số hàng sau khi loại bỏ Quantity <= 0: {df_cleaned.shape[0]}")

# Xóa các hàng có Price <= 0
df_cleaned = df_cleaned[df_cleaned['Price'] > 0]
print(f"Số hàng sau khi loại bỏ Price <= 0: {df_cleaned.shape[0]}")

print(f"Tổng số hàng đã xóa do dữ liệu không hợp lệ: {initial_rows - df_cleaned.shape[0]}")
print("Kích thước DataFrame sau bước này: ", df_cleaned.shape)
display(df_cleaned.head())

Số hàng sau khi loại bỏ Invoice có chữ cái: 400947
Số hàng sau khi loại bỏ Quantity <= 0: 400947
Số hàng sau khi loại bỏ Price <= 0: 400916
Tổng số hàng đã xóa do dữ liệu không hợp lệ: 9847
Kích thước DataFrame sau bước này:  (400916, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

### 4.5. Chuyển đổi kiểu dữ liệu (Convert Data Types)

- `InvoiceDate`: Chuyển sang datetime.
- `Quantity`, `Price`, `CustomerID`: Chuyển sang số nguyên.

In [14]:
print("Kiểu dữ liệu trước khi chuyển đổi:")
display(df_cleaned.info())

# Chuyển InvoiceDate sang datetime
df_cleaned['InvoiceDate'] = pd.to_datetime(df_cleaned['InvoiceDate'])

# Chuyển Quantity, Price, Customer ID sang số nguyên
# Customer ID cần chuyển sang int sau khi đã loại bỏ NaN
df_cleaned['Quantity'] = df_cleaned['Quantity'].astype(int)
df_cleaned['Price'] = df_cleaned['Price'].astype(float) # Đảm bảo Price là float trước khi tạo Amount
df_cleaned['Customer ID'] = df_cleaned['Customer ID'].astype(int)

print("Kiểu dữ liệu sau khi chuyển đổi:")
display(df_cleaned.info())
print("Kích thước DataFrame sau bước này: ", df_cleaned.shape)
display(df_cleaned.head())

Kiểu dữ liệu trước khi chuyển đổi:
<class 'pandas.core.frame.DataFrame'>
Index: 400916 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      400916 non-null  object
 1   StockCode    400916 non-null  object
 2   Description  400916 non-null  object
 3   Quantity     400916 non-null  int64
 4   InvoiceDate  400916 non-null  datetime64[ns]
 5   Price        400916 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      400916 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.5+ MB

None

Kiểu dữ liệu sau khi chuyển đổi:
<class 'pandas.core.frame.DataFrame'>
Index: 400916 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      400916 non-null  object
 1   StockCode    400916 non-null  object
 2   Description  400916 non-null  object
 3   Quantity     400916 non-null  int64
 4   InvoiceDate  400916 non-null  datetime64[ns]
 5   Price        400916 non-null  float64
 6   Customer ID  400916 non-null  int64
 7   Country      400916 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 27.5+ MB

None

Kích thước DataFrame sau bước này:  (400916, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

### 4.6. Tạo các cột mới (Create New Features)

- `Amount`: `Quantity` * `Price`.
- `Year`, `Month`, `Day`, `Hour`, `DayOfWeek`, `MonthYear` từ `InvoiceDate`.

In [15]:
# Tạo cột Amount
df_cleaned['Amount'] = df_cleaned['Quantity'] * df_cleaned['Price']

# Tạo các cột thời gian từ InvoiceDate
df_cleaned['Year'] = df_cleaned['InvoiceDate'].dt.year
df_cleaned['Month'] = df_cleaned['InvoiceDate'].dt.month
df_cleaned['Day'] = df_cleaned['InvoiceDate'].dt.day
df_cleaned['Hour'] = df_cleaned['InvoiceDate'].dt.hour
df_cleaned['DayOfWeek'] = df_cleaned['InvoiceDate'].dt.dayofweek # Monday=0, Sunday=6
df_cleaned['MonthYear'] = df_cleaned['InvoiceDate'].dt.to_period('M')

print("Kích thước DataFrame sau bước này: ", df_cleaned.shape)
display(df_cleaned.head())

Kích thước DataFrame sau bước này:  (400916, 15)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Amount,Year,Month,Day,Hour,DayOfWeek,MonthYear
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,1,7,1,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,7,1,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,7,1,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,1,7,1,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,1,7,1,2009-12

### 5. Lưu Trữ Dữ Liệu Đã Làm Sạch

Sau khi hoàn tất quá trình làm sạch và tiền xử lý, dữ liệu sẽ được lưu vào một file CSV mới.

In [16]:
output_file_path = 'cleaned_online_retail.csv'
df_cleaned.to_csv(output_file_path, index=False)
print(f"Dữ liệu đã làm sạch được lưu vào: {output_file_path}")

print("Quá trình làm sạch dữ liệu hoàn tất.")

Dữ liệu đã làm sạch được lưu vào: cleaned_online_retail.csv
Quá trình làm sạch dữ liệu hoàn tất.

## 🚀 Tự Động Chạy Toàn Bộ Quy Trình Làm Sạch Dữ Liệu

Phần này sẽ tự động chạy tất cả các bước đã định nghĩa ở trên để làm sạch dữ liệu và xuất ra file CSV cuối cùng.

In [18]:
import pandas as pd
import numpy as np

# --- 1. Tải Dữ Liệu ---
file_path = '/content/online_retail_II.xlsx'
try:
    df_cleaned = pd.read_excel(file_path)
    print("Đã tải dữ liệu thành công từ sheet mặc định.")
except ValueError as e:
    if "Multiple sheets found" in str(e):
        print("Phát hiện nhiều sheet. Đang đọc sheet 'Year 2010-2011' (thường là sheet chính).")
        df_cleaned = pd.read_excel(file_path, sheet_name='Year 2010-2011')
    else:
        print(f"Lỗi khi tải file: {e}")

print(f"Kích thước ban đầu của DataFrame: {df_cleaned.shape}")

# --- 2. Thay đổi tên cột (nếu cần) ---
# print("Tên cột hiện tại:", df_cleaned.columns.tolist())
# Nếu bạn muốn đổi tên, hãy bỏ comment dòng dưới và tùy chỉnh:
# df_cleaned = df_cleaned.rename(columns={'Mã hóa đơn': 'InvoiceNo', 'Mô tả': 'Description'})
print("Đã kiểm tra tên cột, không đổi tên mặc định.")

# --- 3. Xóa các hàng trùng lặp ---
initial_rows_dup = df_cleaned.shape[0]
df_cleaned.drop_duplicates(inplace=True)
print(f"Số hàng sau khi xóa trùng lặp: {df_cleaned.shape[0]} (Đã xóa {initial_rows_dup - df_cleaned.shape[0]} hàng)")

# --- 4. Xử lý thiếu dữ liệu ---
initial_rows_nan = df_cleaned.shape[0]
df_cleaned.dropna(subset=['Customer ID', 'Description'], inplace=True)
print(f"Số hàng sau khi xóa thiếu dữ liệu: {df_cleaned.shape[0]} (Đã xóa {initial_rows_nan - df_cleaned.shape[0]} hàng)")

# --- 5. Xử lý dữ liệu không hợp lệ ---
initial_rows_invalid = df_cleaned.shape[0]
df_cleaned = df_cleaned[~df_cleaned['Invoice'].astype(str).str.contains('[A-Za-z]', na=False)]
df_cleaned = df_cleaned[df_cleaned['Quantity'] > 0]
df_cleaned = df_cleaned[df_cleaned['Price'] > 0]
print(f"Số hàng sau khi loại bỏ dữ liệu không hợp lệ: {df_cleaned.shape[0]} (Đã xóa {initial_rows_invalid - df_cleaned.shape[0]} hàng)")

# --- 6. Chuyển đổi kiểu dữ liệu ---
df_cleaned['InvoiceDate'] = pd.to_datetime(df_cleaned['InvoiceDate'])
df_cleaned['Quantity'] = df_cleaned['Quantity'].astype(int)
df_cleaned['Price'] = df_cleaned['Price'].astype(float)
df_cleaned['Customer ID'] = df_cleaned['Customer ID'].astype(int)
print("Đã chuyển đổi kiểu dữ liệu.")

# --- 7. Tạo các cột mới ---
df_cleaned['Amount'] = df_cleaned['Quantity'] * df_cleaned['Price']
df_cleaned['Year'] = df_cleaned['InvoiceDate'].dt.year
df_cleaned['Month'] = df_cleaned['InvoiceDate'].dt.month
df_cleaned['Day'] = df_cleaned['InvoiceDate'].dt.day
df_cleaned['Hour'] = df_cleaned['InvoiceDate'].dt.hour
df_cleaned['DayOfWeek'] = df_cleaned['InvoiceDate'].dt.dayofweek
df_cleaned['MonthYear'] = df_cleaned['InvoiceDate'].dt.to_period('M')
print("Đã tạo các cột tính năng mới.")

# --- 8. Lưu Trữ Dữ Liệu Đã Làm Sạch ---
output_file_path = 'cleaned_online_retail.csv'
df_cleaned.to_csv(output_file_path, index=False)
print(f"Dữ liệu đã làm sạch được lưu vào: {output_file_path}")

print("\n--- Quy trình làm sạch dữ liệu hoàn tất! --- ")
display(df_cleaned.head())

Đã tải dữ liệu thành công từ sheet mặc định.
Kích thước ban đầu của DataFrame: (525461, 8)
Đã kiểm tra tên cột, không đổi tên mặc định.
Số hàng sau khi xóa trùng lặp: 518596 (Đã xóa 6865 hàng)
Số hàng sau khi xóa thiếu dữ liệu: 410763 (Đã xóa 107833 hàng)
Số hàng sau khi loại bỏ dữ liệu không hợp lệ: 400916 (Đã xóa 9847 hàng)
Đã chuyển đổi kiểu dữ liệu.
Đã tạo các cột tính năng mới.
Dữ liệu đã làm sạch được lưu vào: cleaned_online_retail.csv

--- Quy trình làm sạch dữ liệu hoàn tất! ---

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Amount,Year,Month,Day,Hour,DayOfWeek,MonthYear
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,1,7,1,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,7,1,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,7,1,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,1,7,1,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,1,7,1,2009-12